package cn.ftoutiao.account.android.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.ftoutiao.account.android.model.db.ATypeListEntity;
import cn.ftoutiao.account.android.model.db.CategoryEntity;
import cn.ftoutiao.account.android.model.db.ListItemBO;

import cn.ftoutiao.account.android.db.dao.ATypeListEntityDao;
import cn.ftoutiao.account.android.db.dao.CategoryEntityDao;
import cn.ftoutiao.account.android.db.dao.ListItemBODao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aTypeListEntityDaoConfig;
    private final DaoConfig categoryEntityDaoConfig;
    private final DaoConfig listItemBODaoConfig;

    private final ATypeListEntityDao aTypeListEntityDao;
    private final CategoryEntityDao categoryEntityDao;
    private final ListItemBODao listItemBODao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aTypeListEntityDaoConfig = daoConfigMap.get(ATypeListEntityDao.class).clone();
        aTypeListEntityDaoConfig.initIdentityScope(type);

        categoryEntityDaoConfig = daoConfigMap.get(CategoryEntityDao.class).clone();
        categoryEntityDaoConfig.initIdentityScope(type);

        listItemBODaoConfig = daoConfigMap.get(ListItemBODao.class).clone();
        listItemBODaoConfig.initIdentityScope(type);

        aTypeListEntityDao = new ATypeListEntityDao(aTypeListEntityDaoConfig, this);
        categoryEntityDao = new CategoryEntityDao(categoryEntityDaoConfig, this);
        listItemBODao = new ListItemBODao(listItemBODaoConfig, this);

        registerDao(ATypeListEntity.class, aTypeListEntityDao);
        registerDao(CategoryEntity.class, categoryEntityDao);
        registerDao(ListItemBO.class, listItemBODao);
    }
    
    public void clear() {
        aTypeListEntityDaoConfig.clearIdentityScope();
        categoryEntityDaoConfig.clearIdentityScope();
        listItemBODaoConfig.clearIdentityScope();
    }

    public ATypeListEntityDao getATypeListEntityDao() {
        return aTypeListEntityDao;
    }

    public CategoryEntityDao getCategoryEntityDao() {
        return categoryEntityDao;
    }

    public ListItemBODao getListItemBODao() {
        return listItemBODao;
    }

}
